const fs=require('fs'),vm=require('vm'),assert=require('assert');
let memory=new Map();let ctx=vm.createContext({document:{addEventListener(){}},window:{addEventListener(){}},console,Intl,Date,localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},assert});
vm.runInContext(require('./source-core.cjs'),ctx);
vm.runInContext(`
let tests=[];const check=(name,fn)=>{fn();tests.push(name)};
check('Démonstration mathématiquement valide',()=>{validateDB(makeDemo())});
let d=emptyDB(),r=(k,n)=>d.refs[k].find(x=>x.name===n).id,loc=r('locations','Rayon'),reserve=r('locations','Réserve'),f={date:today(),time:'10:00',location:loc,supplier:'',employee:''};
let b=productSave(d,{name:'Biscuits',category:r('categories','Alimentation'),unit:r('units','unité'),type:'discrete',min:5,target:100,packs:[{id:'B',name:'Biscuit',ratio:1,parent:'',sellable:true,active:true},{id:'P',name:'Paquet',ratio:12,parent:'',sellable:true,active:true},{id:'C',name:'Carton',ratio:4,parent:'P',sellable:true,active:true}]});
check('Conversion carton 4 × 12 = 48',()=>assert.equal(factor(b,'C'),48));
receive(d,{...f,product:b.id,pack:'C',qty:2,price:2400});
for(let k of b.packs)tariff(d,{product:b.id,pack:k.id,desired:25,price:factor(b,k.id)*100,effective:today()+'T00:00'});
let sf={...f,payment:r('payments','Espèce'),customer:''};
check('Vente 1 carton + 2 paquets + 3 biscuits retire 75',()=>{checkoutCore(d,sf,[{product:b.id,pack:'C',qty:1,location:loc},{product:b.id,pack:'P',qty:2,location:loc},{product:b.id,pack:'B',qty:3,location:loc}]);assert.equal(stock(b),21)});
check('Transfert interne conserve le stock',()=>{adjust(d,{...f,product:b.id,type:'Transfert interne',qty:10,to:reserve,note:'Rayon réserve'});assert.equal(stock(b),21);assert.equal(b.balances[reserve],10)});
check('Coût historique immuable',()=>{let old=JSON.stringify(d.sales[0]);receive(d,{...f,product:b.id,pack:'C',qty:1,price:4800});assert.equal(JSON.stringify(d.sales[0]),old)});
let w=productSave(d,{name:'Cuisses',category:r('categories','Viandes & volailles'),unit:r('units','kg'),type:'weight',min:0,target:100,packs:[{id:'kg',name:'kg',ratio:1,parent:'',sellable:true,free:true},{id:'half',name:'Demi kilo',ratio:.5,parent:'',sellable:true},{id:'box',name:'Carton',ratio:10,parent:'',sellable:true}]});receive(d,{...f,product:w.id,pack:'box',qty:10,price:10000});for(let k of w.packs)tariff(d,{product:w.id,pack:k.id,desired:25,price:factor(w,k.id)*1500,effective:today()+'T00:00'});
check('Poids 1 + 0,5 + 1,75 kg',()=>{checkoutCore(d,sf,[{product:w.id,pack:'kg',qty:1,location:loc},{product:w.id,pack:'half',qty:1,location:loc},{product:w.id,pack:'kg',qty:1.75,location:loc}]);assert.equal(stock(w),96.75)});
let inv=inventoryCreate(d,{...f,label:'Comptage',location:loc});
check('Inventaire biscuits 175 et poids 46,5',()=>{inventoryCount(d,inv.id,0,[7,2,3],'');inventoryCount(d,inv.id,1,[6.5,0,4],'');assert.equal(inv.lines[0].physical,175);assert.equal(inv.lines[1].physical,46.5);let snapshot=inv.lines[0].theoretical;inventoryValidate(d,inv.id);assert.equal(inv.lines[0].theoretical,snapshot);assert.equal(b.balances[loc],175);assert.equal(w.balances[loc],46.5);assert.throws(()=>inventoryValidate(d,inv.id));validateDB(d)});
check('Promotion active, expiration, tarif normal conservé',()=>{let pro=promotion(d,{name:'Promotion',product:b.id,pack:'B',start:today()+'T09:00',end:today()+'T11:00',price:80});assert.equal(selling(d,b,b.packs[0],today()+'T10:00').price,80);assert.equal(selling(d,b,b.packs[0],today()+'T12:00').price,100)});
for(let name of ['Huri','Yas'])d.sims.push({id:code(d,'SIM'),name,operator:r('operators',name),services:['Transfert crédit','Mobile Money'],balance:0,opening:0,active:true});
check('Huri reçu 50 000 payé 47 500 commission 2 500',()=>{let t=telecom(d,{...f,sim:d.sims[0].id,type:'Réapprovisionnement',amount:50000,paid:47500});assert.equal(t.commission,2500);assert.equal(t.after,50000)});
check('Yas commission manuelle et solde partagé Mobile Money',()=>{let sim=d.sims[1];telecom(d,{...f,sim:sim.id,type:'Réapprovisionnement',amount:50000,paid:50000});telecom(d,{...f,sim:sim.id,type:'Transfert crédit',amount:2000});telecom(d,{...f,sim:sim.id,type:'Commission reçue',amount:735});telecom(d,{...f,sim:sim.id,type:'Dépôt',amount:5000,commission:0});telecom(d,{...f,sim:sim.id,type:'Retrait',amount:3000,commission:0});assert.equal(sim.balance,46735);validateDB(d)});
check('Sauvegarde, réinitialisation, restauration exacte et compteurs',()=>{db=d;storageText=null;localStorage.setItem(KEY,JSON.stringify(db));storageText=localStorage.getItem(KEY);let out=backupData();assert.match(out.name,/BoutiquePilot_SAUV_\\d{2}-\\d{2}-\\d{4}_01.json/);let saved=JSON.stringify(db);replaceDB(emptyDB());replaceDB(migrate(JSON.parse(out.text)));assert.equal(JSON.stringify(db),saved);assert.ok(backupData().name.endsWith('_02.json'))});
check('Transaction annulée intégralement si stock insuffisant',()=>{let before=JSON.stringify(db);assert.throws(()=>transact(d=>checkoutCore(d,sf,[{product:b.id,pack:'B',qty:1,location:loc},{product:b.id,pack:'C',qty:10000,location:loc}])));assert.equal(JSON.stringify(db),before)});
check('Refus sauvegarde invalide sans modification',()=>{let before=JSON.stringify(db),bad=clone(db);bad.products[0].balances[loc]=-1;assert.throws(()=>replaceDB(bad));assert.equal(JSON.stringify(db),before)});
check('Démonstration reproductible après modifications',()=>{let initial=makeDemo();let altered=clone(initial);altered.store.name='Modifié';assert.deepEqual(makeDemo(),initial)});
console.log(JSON.stringify({passed:tests.length,tests},null,2));
`,ctx);
