import sharp from 'sharp';
import {readFile,mkdir,writeFile,copyFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const play='resources/play';
await mkdir(play,{recursive:true});
await sharp('resources/icon.png').resize(512,512,{fit:'contain'}).png().toFile(`${play}/icone-google-play-512.png`);
const logo=(await sharp('resources/launch-logo.png').resize(400,400,{fit:'contain'}).png().toBuffer()).toString('base64');
const feature=`<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500"><rect width="1024" height="500" fill="#f5f9fc"/><path d="M660 0H1024V500H830Z" fill="#e7f4fc"/><image href="data:image/png;base64,${logo}" x="48" y="75" width="320" height="320"/><g font-family="Segoe UI,Arial,sans-serif" fill="#132f4c"><text x="420" y="165" font-size="52" font-weight="700">BoutiquePilot</text><text x="422" y="220" font-size="24" fill="#087cb4" letter-spacing="3">BÊTA ANDROID</text><text x="422" y="285" font-size="28">Ventes, stocks et sauvegardes.</text><text x="422" y="330" font-size="28">Votre boutique, hors connexion.</text><text x="422" y="401" font-size="18" letter-spacing="3">MORA SHAWIRI</text></g></svg>`;
await writeFile(`${play}/feature-graphic-1024x500.svg`,feature);
await sharp(Buffer.from(feature)).flatten({background:'#f5f9fc'}).removeAlpha().png().toFile(`${play}/feature-graphic-1024x500.png`);
console.log('Play icon and feature graphic prepared. Use campaign-final.mjs from the repository root for final campaign PNGs.');
