import sharp from 'sharp';
import {readFile,mkdir,writeFile,copyFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const play='resources/play',templates='resources/campaign-templates';
await mkdir(play,{recursive:true});await mkdir(templates,{recursive:true});
await sharp('resources/icon.png').resize(512,512,{fit:'contain'}).png().toFile(`${play}/icone-google-play-512.png`);
const logo=(await sharp('resources/launch-logo.png').resize(400,400,{fit:'contain'}).png().toBuffer()).toString('base64');
const feature=`<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500"><rect width="1024" height="500" fill="#f5f9fc"/><path d="M660 0H1024V500H830Z" fill="#e7f4fc"/><image href="data:image/png;base64,${logo}" x="48" y="75" width="320" height="320"/><g font-family="Segoe UI,Arial,sans-serif" fill="#132f4c"><text x="420" y="165" font-size="52" font-weight="700">BoutiquePilot</text><text x="422" y="220" font-size="24" fill="#087cb4" letter-spacing="3">BÊTA ANDROID</text><text x="422" y="285" font-size="28">Ventes, stocks et sauvegardes.</text><text x="422" y="330" font-size="28">Votre boutique, hors connexion.</text><text x="422" y="401" font-size="18" letter-spacing="3">MORA SHAWIRI</text></g></svg>`;
await writeFile(`${play}/feature-graphic-1024x500.svg`,feature);
await sharp(Buffer.from(feature)).flatten({background:'#f5f9fc'}).removeAlpha().png().toFile(`${play}/feature-graphic-1024x500.png`);
const specs=[['01-tableau-de-bord',['Votre activité,','en un coup d’œil.'],'Tableau de bord'],['02-caisse-panier',['Encaissez et suivez','vos ventes.'],'Caisse / panier'],['03-articles-stock',['Gardez le contrôle','de votre stock.'],'Articles / stock'],['04-tarification-marges',['Consultez vos prix','et vos marges.'],'Tarification / marges']];
for(const [name,lines,caption] of specs){
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><defs><linearGradient id="bg" x2="1" y2="1"><stop stop-color="#132f4c"/><stop offset="1" stop-color="#072139"/></linearGradient></defs><rect width="1080" height="1350" fill="url(#bg)"/><circle cx="1000" cy="280" r="360" fill="#087cb4" opacity=".18"/><rect x="65" y="55" width="146" height="146" rx="24" fill="#fff"/><image href="data:image/png;base64,${logo}" x="70" y="60" width="136" height="136"/><g font-family="Segoe UI,Arial,sans-serif"><text x="250" y="112" fill="#fff" font-size="39" font-weight="700">BoutiquePilot</text><text x="252" y="158" fill="#55c8ff" font-size="22" letter-spacing="3">BÊTA ANDROID · MORA SHAWIRI</text><text x="65" y="284" fill="#fff" font-size="57" font-weight="700">${lines[0]}</text><text x="65" y="354" fill="#fff" font-size="57" font-weight="700">${lines[1]}</text><rect x="310" y="410" width="460" height="755" rx="28" fill="#f0f6fa" stroke="#59c8ff" stroke-width="3" stroke-dasharray="12 8"/><text x="540" y="700" text-anchor="middle" fill="#132f4c" font-size="24" font-weight="700">${caption}</text><text x="540" y="755" text-anchor="middle" fill="#40566a" font-size="21">Capture Android validée</text><text x="540" y="790" text-anchor="middle" fill="#40566a" font-size="21">à insérer</text><text x="540" y="865" text-anchor="middle" fill="#64798b" font-size="17">MODÈLE — NE PAS PUBLIER</text><text x="65" y="1240" fill="#fff" font-size="27">Données sur votre appareil. Sauvegardes JSON.</text><text x="65" y="1290" fill="#78bddf" font-size="23">boutiquepilot.morashawiri.com</text></g></svg>`;
await writeFile(`${templates}/${name}-MODELE.svg`,svg);
const destination=resolve('../../07 Application Mobile Bêta/03 Captures App/Campagne App');await mkdir(destination,{recursive:true});await copyFile(`${templates}/${name}-MODELE.svg`,resolve(destination,`${name}-MODELE.svg`));
}
await sharp(await readFile(`${templates}/01-tableau-de-bord-MODELE.svg`)).resize(540,675).png().toFile('artifacts/campaign-template-preview.png');
console.log('Play icon, feature graphic and exactly four draft campaign structures prepared.');
